---
- name: Clean data from nodes
  gather_facts: true
  hosts: all
  become: "{{ use_sudo }}"
  become_method: sudo
  become_user: root
  tasks:
    - name: Remove data from nodes
      file:
        path: "{{node_wd}}"
        state: absent
