---
- name: Get data from nodes
  gather_facts: true
  hosts: all
  become: "{{ lookup('env', 'ANSIBLE_USE_SUDO') | default('false') == 'true' }}"
  become_method: sudo
  become_user: root
  tasks:
    - name: Get data from nodes
      ansible.posix.synchronize:
        src: "{{node_wd}}"
        dest: "{{dest}}"
        mode: pull
    - debug:
        msg: "Output files have been written to {{dest}}"
