---
- name: Stop PaperMC
  gather_facts: true
  hosts: all
  tasks:
    - name: Find PaperMC PID
      shell: |
        cat {{wd}}/papermc.pid
      register: shell_papermc_pid
    - name: Obtain PaperMC pid
      set_fact:
        papermc_pid: "{{ shell_papermc_pid.stdout }}"
    - name: Stop PaperMC
      shell: |
        kill {{papermc_pid}}
    - name: Wait for PaperMC to stop
      block:
        - wait_for:
            # Using https://stackoverflow.com/questions/46515704/how-to-kill-a-running-process-using-ansible/46541018#46541018
            path: "/proc/{{ papermc_pid }}/status"
            state: absent
            timeout: 15
          register: wait_for_stop
      rescue:
        - name: Force kill stuck processes
          shell: |
            kill -9 {{papermc_pid}}
