---
- name: Deploy PaperMC
  gather_facts: true
  hosts: all
  tasks:
    - file:
        path: "{{ wd }}"
        state: directory
    - name: Download PaperMC
      get_url:
        url: https://api.papermc.io/v2/projects/paper/versions/1.20.1/builds/58/downloads/paper-1.20.1-58.jar
        dest: "{{ wd }}/paper-1.20.1-58.jar"
    - name: Copy config file
      template:
        src: "{{papermc_template}}"
        dest: "{{wd}}/server.properties" 
    - name: Accept EULA
      copy:
        content: "eula=true"
        dest: "{{ wd }}/eula.txt"
    - name: Download Jolokia JVM Agent
      get_url:
        url: https://search.maven.org/remotecontent?filepath=org/jolokia/jolokia-agent-jvm/2.0.3/jolokia-agent-jvm-2.0.3-javaagent.jar
        dest: "{{wd}}/jolokia-agent-jvm-2.0.3-javaagent.jar"
