---
- name: Start Rust WalkAround bots
  hosts: all
  environment:
    TMPDIR: "{{ wd }}/tmp"
    TEMP: "{{ wd }}/tmp"
    TMP: "{{ wd }}/tmp"
  tasks:
    - name: Start multiple walkbots
      shell: |
        source ~/.cargo/env
        nohup cargo run --release --bin multi_walkbot -- \
          --server {{ server_host }}:{{ server_port }} \
          --count {{ bots_per_node }} \
          --mode {{ movement_mode }} \
          --speed {{ movement_speed }} \
          --duration {{ duration_seconds | int }} \
          > /tmp/walkbot_{{ inventory_hostname }}.log 2>&1 &
      args:
        chdir: "{{ texmodbot_path }}"
      environment:
        CARGO_HOME: ~/.cargo

    - name: Wait for bots to initialize
      pause:
        seconds: 5
