---
- name: Deploy Rust WalkAround bots
  hosts: all
  tasks:
    - name: Debug path information
      debug:
        msg: |
          Working directory: {{ wd }}
          Texmodbot path: {{ texmodbot_path }}
          Current user: {{ ansible_user | default('unknown') }}
          Home directory: {{ ansible_env.HOME | default('unknown') }}

    - name: Install Rust if not present
      shell: |
        if ! command -v cargo &> /dev/null; then
          curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
          source ~/.cargo/env
          rustup install nightly
          rustup default nightly
        fi

    - name: Create texmodbot directory with parents
      file:
        path: "{{ texmodbot_path }}"
        state: directory
        mode: "0755"
        recurse: yes

    - name: Verify texmodbot directory exists
      stat:
        path: "{{ texmodbot_path }}"
      register: texmodbot_dir_check

    - name: Fail if texmodbot directory not created
      fail:
        msg: "Failed to create texmodbot directory at {{ texmodbot_path }}"
      when: not texmodbot_dir_check.stat.exists

    - name: Copy texmodbot source code
      synchronize:
        src: "{{ texmodbot_source }}/"
        dest: "{{ texmodbot_path }}/"
        delete: yes
        recursive: yes
      delegate_to: localhost
      
    - name: Verify source code was copied
      stat:
        path: "{{ texmodbot_path }}/Cargo.toml"
      register: cargo_toml_check
      
    - name: Fail if Cargo.toml not found
      fail:
        msg: "Cargo.toml not found in {{ texmodbot_path }}. Source copy may have failed."
      when: not cargo_toml_check.stat.exists

    - name: Build Rust bots
      shell: |
        source ~/.cargo/env
        rustup override set nightly
        cargo build --release --bin multi_walkbot
      args:
        chdir: "{{ texmodbot_path }}"
      environment:
        CARGO_HOME: ~/.cargo
