---
- name: Deploy nullblock
  gather_facts: true
  hosts: all
  become: "{{ lookup('env', 'ANSIBLE_USE_SUDO') | default('false') == 'true' }}"
  become_method: sudo
  become_user: root
  tasks:
    - name: Create nullblock folder
      file:
        path: "{{wd}}"
        state: directory
    - name: Copy nullblock executable
      copy:
        src: "{{nullblk_script}}"
        dest: "{{wd}}"