---
- name: Virtualize Storage
  gather_facts: true
  hosts: all
  become: "{{ use_sudo }}"
  tasks:
    - name: Make createnullblk executable
      shell:
        cmd: chmod +x {{wd}}/createnullblk.sh
        chdir: "{{wd}}"
    - name: Run create nullblk, set up file system, and mount on the root folder
      shell:
        cmd: ./createnullblk.sh 512 8192 {{storage_latency}} {{throughput}} >> drive.dev
        chdir: "{{wd}}"
    - name: Read the device name from drive.dev file
      shell: cat {{ wd }}/drive.dev
      register: drive_device
      changed_when: false
    - name: Save the device name as a fact
      set_fact:
        saved_device: "{{ drive_device.stdout }}"
        cacheable: yes
    - name: Make fs on the drive
      shell:
        cmd: mkfs.ext4 /dev/{{saved_device}}
    - name: Mount drive onto working directory
      shell:
        cmd: mount /dev/{{saved_device}} {{node_wd}}
    - name: Write device name inside virtualized storage
      shell:
        cmd: echo {{saved_device}} >> {{node_wd}}/drive.dev