---
- name: Deploy Luanti Server
  gather_facts: true
  hosts: all
  become: yes
  tasks:
    - name: Update package cache
      apt:
        update_cache: yes
      when: ansible_os_family == "Debian"

    - name: Install build dependencies
      package:
        name:
          - build-essential
          - cmake
          - git
          - libirrlicht-dev
          - libjpeg-dev
          - libpng-dev
          - libbz2-dev
          - libsqlite3-dev
          - libfreetype6-dev
          - libzstd-dev
          - libcurl4-openssl-dev
          - libluajit-5.1-dev
          - libleveldb-dev
          - libgmp-dev
          - libjsoncpp-dev
          - libhiredis-dev
          - libncurses5-dev
          - gettext
          - wget
          - tar
        state: present
      when: ansible_os_family == "Debian"

    - name: Create working directory
      file:
        path: "{{ wd }}"
        state: directory
        mode: "0755"
      become: no

    - name: Create luanti_server directory
      file:
        path: "{{ wd }}/luanti_server"
        state: directory
        mode: "0755"
      become: no

    - name: Create worlds directory structure
      file:
        path: "{{ wd }}/worlds/benchmark"
        state: directory
        mode: "0755"
      become: no

    - name: Create world.mt file
      copy:
        content: |
          gameid = {{ game_mode }}
          backend = sqlite3
          creative_mode = true
          disable_anticheat = true
          enable_damage = false
        dest: "{{ wd }}/worlds/benchmark/world.mt"
        mode: "0644"
      become: no

    - name: Create mods directory
      file:
        path: "{{ wd }}/worlds/benchmark/mods"
        state: directory
        mode: "0755"
      become: no

    - name: Create yardstick_collector mod directory
      file:
        path: "{{ wd }}/worlds/benchmark/mods/yardstick_collector"
        state: directory
        mode: "0755"
      become: no

    - name: Copy collector mod
      copy:
        src: "{{ collector_mod }}"
        dest: "{{ wd }}/worlds/benchmark/mods/yardstick_collector/init.lua"
        mode: "0644"
      become: no

    - name: Download Luanti 5.11.0 source code
      get_url:
        url: "https://github.com/luanti-org/luanti/archive/refs/tags/5.11.0.tar.gz"
        dest: "{{ wd }}/luanti-5.11.0-source.tar.gz"
        timeout: 120
      become: no

    - name: Extract Luanti source code
      unarchive:
        src: "{{ wd }}/luanti-5.11.0-source.tar.gz"
        dest: "{{ wd }}"
        remote_src: yes
        creates: "{{ wd }}/luanti-5.11.0"
      become: no

    - name: Create build directory
      file:
        path: "{{ wd }}/luanti-5.11.0/build"
        state: directory
        mode: "0755"
      become: no

    - name: Configure Luanti build (server only)
      shell: |
        cd {{ wd }}/luanti-5.11.0/build
        cmake .. \
          -DCMAKE_BUILD_TYPE=Release \
          -DBUILD_CLIENT=FALSE \
          -DBUILD_SERVER=TRUE \
          -DENABLE_GETTEXT=TRUE \
          -DENABLE_FREETYPE=TRUE \
          -DENABLE_LEVELDB=TRUE \
          -DENABLE_REDIS=TRUE \
          -DENABLE_LUAJIT=TRUE
      become: no

    - name: Compile Luanti server
      shell: |
        cd {{ wd }}/luanti-5.11.0/build
        make -j$(nproc) luantiserver
      become: no

    - name: Copy server binary to luanti_server directory
      copy:
        src: "{{ wd }}/luanti-5.11.0/build/bin/luantiserver"
        dest: "{{ wd }}/luanti_server/luantiserver"
        mode: "0755"
        remote_src: yes
      become: no

    - name: Create symlink to server binary for easy access
      file:
        src: "{{ wd }}/luanti_server/luantiserver"
        dest: "{{ wd }}/luanti-server"
        state: link
      become: no

    - name: Copy server configuration (minetest.conf)
      template:
        src: "{{ luanti_template }}"
        dest: "{{ wd }}/minetest.conf"
        mode: "0644"
      become: no

    - name: Create metrics directory (local to working directory)
      file:
        path: "{{ wd }}/metrics"
        state: directory
        mode: "0755"
      become: no

    - name: Create empty mod_storage directory
      file:
        path: "{{ wd }}/worlds/benchmark/mod_storage"
        state: directory
        mode: "0755"
      become: no

    - name: Create empty players directory
      file:
        path: "{{ wd }}/worlds/benchmark/players"
        state: directory
        mode: "0755"
      become: no

    - name: Test server binary
      shell: |
        cd {{ wd }}
        ./luanti-server --version || echo "Server binary test completed"
      become: no
      register: server_test

    - name: Display server build info
      debug:
        msg: |
          Server compilation completed!
          Binary location: {{ wd }}/luanti-server
          Test output: {{ server_test.stdout }}
