---
- name: Deploy Luanti Server
  gather_facts: true
  hosts: all
  tasks:
    - name: Create working directory
      file:
        path: "{{ wd }}"
        state: directory

    - name: Download Luanti Server
      get_url:
        url: https://github.com/luanti-org/luanti/releases/download/5.11.0/luanti-5.11.0-linux-x86_64.tar.gz
        dest: "{{ wd }}/luanti.tar.gz"

    - name: Extract Luanti Server
      unarchive:
        src: "{{ wd }}/luanti.tar.gz"
        dest: "{{ wd }}"
        remote_src: yes

    - name: Create mod directories
      file:
        path: "{{ wd }}/mods/yardstick_collector"
        state: directory

    - name: Copy collector mod
      copy:
        src: "{{ collector_mod }}"
        dest: "{{ wd }}/mods/yardstick_collector/init.lua"

    - name: Create world directory
      file:
        path: "{{ wd }}/worlds/benchmark"
        state: directory

    - name: Copy config file
      template:
        src: "{{ luanti_template }}"
        dest: "{{ wd }}/luanti.conf"
