---
- name: Start Luanti Server
  gather_facts: true
  hosts: all
  tasks:
    - name: Run Luanti server
      shell:
        cmd: |
          cd {{ wd }}
          ./bin/luanti-server --gameid {{ game_mode }} --world worlds/benchmark --config luanti.conf --port 30000 > server.log 2>&1 &
          echo $! > luanti.pid
        chdir: "{{ wd }}"

    - name: Wait for server to start
      wait_for:
        path: "{{ wd }}/server.log"
        search_regex: "Server started"
        timeout: 60
