---
- name: Stop Luanti Server
  gather_facts: true
  hosts: all
  tasks:
    - name: Check if the server is running
      stat:
        path: "{{ wd }}/luanti.pid"
      register: pid_file

    - name: Read PID
      command: cat {{ wd }}/luanti.pid
      register: pid_content
      when: pid_file.stat.exists

    - name: Stop server process gracefully
      shell: kill -TERM {{ pid_content.stdout }}
      when: pid_file.stat.exists and pid_content.stdout is defined
      ignore_errors: yes

    - name: Wait for process to stop
      wait_for:
        path: "/proc/{{ pid_content.stdout }}/status"
        state: absent
        timeout: 30
      when: pid_file.stat.exists and pid_content.stdout is defined
      ignore_errors: yes

    - name: Kill process forcefully if still running
      shell: kill -KILL {{ pid_content.stdout }}
      when: pid_file.stat.exists and pid_content.stdout is defined
      ignore_errors: yes

    - name: Kill any remaining luanti processes
      shell: pkill -f luanti || pkill -f minetest || true
      ignore_errors: yes

    - name: Remove PID file
      file:
        path: "{{ wd }}/luanti.pid"
        state: absent

    - name: Display final server log
      shell: |
        cd {{ wd }}
        echo "=== Final server log (last 10 lines) ==="
        tail -10 server.log || echo "No server log found"
      register: final_log
      ignore_errors: yes

    - name: Show server shutdown status
      debug:
        msg: "{{ final_log.stdout }}"
