---
- name: Deploy Luanti Server
  gather_facts: true
  hosts: all
  become: yes
  tasks:
    - name: Update package cache
      apt:
        update_cache: yes
      when: ansible_os_family == "Debian"

    - name: Install required packages
      package:
        name:
          - wget
          - tar
          - sqlite3
          - build-essential
          - node-exporter
        state: present
      when: ansible_os_family == "Debian"

    - name: Create working directory
      file:
        path: "{{ wd }}"
        state: directory
        mode: "0755"

    - name: Create mods directory
      file:
        path: "{{ wd }}/worlds/benchmark/mods"
        state: directory
        mode: "0755"

    - name: Create yardstick_collector mod directory
      file:
        path: "{{ wd }}/worlds/benchmark/mods/yardstick_collector"
        state: directory
        mode: "0755"

    - name: Copy collector mod
      copy:
        src: "{{ collector_mod }}"
        dest: "{{ wd }}/worlds/benchmark/mods/yardstick_collector/init.lua"
        mode: "0644"

    - name: Download Luanti Server (try multiple sources)
      get_url:
        url: "{{ item }}"
        dest: "{{ wd }}/luanti.tar.gz"
        timeout: 30
      loop:
        - https://github.com/luanti-org/luanti/releases/download/5.11.0/luanti-5.11.0-linux-x86_64.tar.gz
        - https://github.com/minetest/minetest/releases/download/5.8.0/minetest-5.8.0-linux.tar.gz
      register: download_result
      until: download_result is succeeded
      retries: 3
      delay: 10
      ignore_errors: yes

    - name: Extract Luanti Server
      unarchive:
        src: "{{ wd }}/luanti.tar.gz"
        dest: "{{ wd }}"
        remote_src: yes
        creates: "{{ wd }}/bin"
      when: download_result is succeeded

    - name: Find server binary
      find:
        paths: "{{ wd }}"
        patterns: "*server*"
        file_type: file
        recurse: yes
      register: server_binaries

    - name: Create symlink to server binary
      file:
        src: "{{ server_binaries.files[0].path }}"
        dest: "{{ wd }}/luanti-server"
        state: link
      when: server_binaries.files | length > 0

    - name: Copy server configuration
      template:
        src: "{{ luanti_template }}"
        dest: "{{ wd }}/luanti.conf"
        mode: "0644"

    - name: Create metrics directory
      file:
        path: /var/lib/node_exporter
        state: directory
        mode: "0755"

    - name: Start node_exporter
      systemd:
        name: node_exporter
        state: started
        enabled: yes
