[[inputs.cpu]]

[[outputs.influxdb_v2]]
  urls = ["http://localhost:8086"]
  token = "BTVniH3XC2fD7NLagSJGYzjHI1QDxC-SGbdaldlTGZua1jzCMfe-7VJ3BjBEIvWGNJGrpNzkI85SsnJCsAh1qA=="
  organization = "a"
  bucket = "a"
