---
- name: Deploy Minecraft WalkAround workload
  gather_facts: true
  hosts: all
  tasks:
    - debug:
        msg: "working directory is: {{wd}}"
    - file:
        path: "{{ wd }}"
        state: directory
    - name: Check if nvm is available
      shell: |
        export NVM_DIR="$HOME/.nvm"
        [ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"
        nvm --version
      register: nvm_version
      failed_when: nvm_version.rc != 0 and nvm_version.rc != 127
    - name: Install nvm
      shell: |
        wget -qO- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.2/install.sh | bash
      when: nvm_version.rc == 127
      async: 7200
      poll: 5
    - name: Install node 18 and Mineflayer
      shell:
        cmd: |
          export NVM_DIR="$HOME/.nvm"
          [ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"
          nvm install 18
          npm install mineflayer
          npm install mineflayer-pathfinder
          npm install mineflayer-collectblock
          npm install mineflayer-tool
          nvm which 18 > {{wd}}/.node_path
        chdir: "{{wd}}"
      async: 7200
      poll: 5
    - name: Copy scripts
      copy:
        src: "{{item}}"
        dest: "{{wd}}"
      with_items: "{{scripts}}"
    - name: Copy bundled RCON client
      copy:
        src: "{{ item }}"
        dest: "{{wd}}/"
      with_items:
        - "{{ scripts[0] | dirname }}/RCON.js"
        - "{{ scripts[0] | dirname }}/Packet.js"
    - name: Set game spawn location
      shell:
        cmd: |
          export NVM_DIR="$HOME/.nvm"
          [ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"
          node set_spawn.js
        chdir: "{{wd}}"
      environment:
        MC_HOST: "{{mc_host}}"
        SPAWN_X: "{{spawn_x}}"
        SPAWN_Y: "{{spawn_y}}"
      run_once: true
      ignore_errors: yes
