global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: 'process-exporter'
    static_configs:
      - targets: ['TERRASTICK_IP:9256']
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['TERRASTICK_IP:9100']