# premetheus config file for scraping metrics from the terrastick app linked to a process exporter

global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'terrastick-server'
    static_configs:
      - targets: ['${TERRASTICK_IP:?You need to set the TERRASTICK_IP environment variable}:9256']
