---
- name: Get data from nodes
  gather_facts: true
  hosts: all
  tasks:
    - name: Get data from nodes
      ansible.posix.synchronize:
        src: "{{node_wd}}"
        dest: "{{dest}}"
        mode: pull
    - debug:
        msg: "Output files have been written to {{dest}}"
