/*
Copyright (c) 2013, DarkStorm (darkstorm@evilminecraft.net)
All rights reserved.

Redistribution and use in source and binary forms, with or without
modification, are permitted provided that the following conditions are met:

1. Redistributions of source code must retain the above copyright notice, this
list of conditions and the following disclaimer.
2. Redistributions in binary form must reproduce the above copyright notice,
this list of conditions and the following disclaimer in the documentation
and/or other materials provided with the distribution.

THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR
ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
(INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
(INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */
package nl.tudelft.opencraft.yardstick.bot.world;

import nl.tudelft.opencraft.yardstick.bot.inventory.ToolType;
import static nl.tudelft.opencraft.yardstick.bot.inventory.ToolType.*;
import static nl.tudelft.opencraft.yardstick.bot.world.Material.Flag.*;

public enum Material {

    UNKNOWN(-1),
    AIR(0, 0),
    STONE(1, SOLID, PICKAXE),
    GRASS(2, SOLID, SHOVEL),
    DIRT(3, SOLID, SHOVEL),
    COBBLESTONE(4, SOLID, PICKAXE),
    WOOD(5, SOLID, AXE),
    SAPLING(6, INTERACTABLE),
    BEDROCK(7, SOLID | PLACEABLE | INDESTRUCTABLE),
    WATER(8, INDESTRUCTABLE),
    STATIONARY_WATER(9, INDESTRUCTABLE),
    LAVA(10, INDESTRUCTABLE),
    STATIONARY_LAVA(11, INDESTRUCTABLE),
    SAND(12, SOLID, SHOVEL),
    GRAVEL(13, SOLID, SHOVEL),
    GOLD_ORE(14, SOLID, PICKAXE),
    IRON_ORE(15, SOLID, PICKAXE),
    COAL_ORE(16, SOLID, PICKAXE),
    LOG(17, SOLID, AXE),
    LEAVES(18, SHEARS),
    SPONGE(19, SOLID),
    GLASS(20, SOLID, PICKAXE),
    LAPIS_ORE(21, SOLID, PICKAXE),
    LAPIS_BLOCK(22, SOLID, PICKAXE),
    DISPENSER(23, SOLID | INTERACTABLE | PLACEABLE, PICKAXE),
    SANDSTONE(24, SOLID, PICKAXE),
    NOTE_BLOCK(25, SOLID | INTERACTABLE | PLACEABLE, PICKAXE),
    BED_BLOCK(26, SOLID | INTERACTABLE | PLACEABLE),
    POWERED_RAIL(27, PLACEABLE, PICKAXE),
    DETECTOR_RAIL(28, PLACEABLE, PICKAXE),
    PISTON_STICKY_BASE(29, PICKAXE),
    WEB(30, PLACEABLE, SWORD),
    LONG_GRASS(31, PLACEABLE),
    DEAD_BUSH(32, PLACEABLE),
    PISTON_BASE(33, SOLID, PICKAXE),
    PISTON_EXTENSION(34, SOLID, PICKAXE),
    WOOL(35, SOLID, SWORD),
    PISTON_MOVING_PIECE(36),
    YELLOW_FLOWER(37, PLACEABLE),
    RED_ROSE(38, PLACEABLE),
    BROWN_MUSHROOM(39, PLACEABLE),
    RED_MUSHROOM(40, PLACEABLE),
    GOLD_BLOCK(41, SOLID, PICKAXE),
    IRON_BLOCK(42, SOLID, PICKAXE),
    DOUBLE_STEP(43, SOLID, PICKAXE),
    STEP(44, PICKAXE),
    BRICK(45, SOLID, PICKAXE),
    TNT(46),
    BOOKSHELF(47, SOLID, AXE),
    MOSSY_COBBLESTONE(48, SOLID, PICKAXE),
    OBSIDIAN(49, SOLID, PICKAXE),
    TORCH(50, PLACEABLE),
    FIRE(51, INDESTRUCTABLE),
    MOB_SPAWNER(52, SOLID, PICKAXE),
    WOOD_STAIRS(53, SOLID, AXE),
    CHEST(54, SOLID | INTERACTABLE | PLACEABLE, AXE),
    REDSTONE_WIRE(55, PLACEABLE),
    DIAMOND_ORE(56, SOLID, PICKAXE),
    DIAMOND_BLOCK(57, SOLID, PICKAXE),
    WORKBENCH(58, SOLID | INTERACTABLE | PLACEABLE, AXE),
    CROPS(59, PLACEABLE),
    SOIL(60, SOLID, SHOVEL),
    FURNACE(61, SOLID | INTERACTABLE | PLACEABLE, PICKAXE),
    BURNING_FURNACE(62, SOLID | INTERACTABLE | PLACEABLE, PICKAXE),
    SIGN_POST(63, PLACEABLE, 16, AXE),
    WOODEN_DOOR(64, SOLID | INTERACTABLE | PLACEABLE, AXE),
    LADDER(65, PLACEABLE),
    RAILS(66, PLACEABLE, PICKAXE),
    COBBLESTONE_STAIRS(67, SOLID, PICKAXE),
    WALL_SIGN(68, PLACEABLE, AXE),
    LEVER(69, INTERACTABLE | PLACEABLE),
    STONE_PLATE(70, PLACEABLE, PICKAXE),
    IRON_DOOR_BLOCK(71, PICKAXE),
    WOOD_PLATE(72, PLACEABLE, AXE),
    REDSTONE_ORE(73, SOLID, PICKAXE),
    GLOWING_REDSTONE_ORE(74, PICKAXE),
    REDSTONE_TORCH_OFF(75, PLACEABLE),
    REDSTONE_TORCH_ON(76, PLACEABLE),
    STONE_BUTTON(77, INTERACTABLE | PLACEABLE, PICKAXE),
    SNOW(78, PLACEABLE, SHOVEL),
    ICE(79, SOLID, PICKAXE),
    SNOW_BLOCK(80, SOLID, SHOVEL),
    CACTUS(81),
    CLAY(82, SOLID, SHOVEL),
    SUGAR_CANE_BLOCK(83, PLACEABLE),
    JUKEBOX(84, SOLID, PICKAXE),
    FENCE(85, SOLID, AXE),
    PUMPKIN(86, AXE),
    NETHERRACK(87, SOLID, PICKAXE),
    SOUL_SAND(88, SOLID, SHOVEL),
    GLOWSTONE(89, SOLID, PICKAXE),
    PORTAL(90, PLACEABLE | INDESTRUCTABLE),
    JACK_O_LANTERN(91, SOLID, AXE),
    CAKE_BLOCK(92),
    DIODE_BLOCK_OFF(93, INTERACTABLE | PLACEABLE),
    DIODE_BLOCK_ON(94, INTERACTABLE | PLACEABLE),
    LOCKED_CHEST(95, AXE),
    TRAP_DOOR(96, AXE),
    MONSTER_EGGS(97),
    SMOOTH_BRICK(98, SOLID, PICKAXE),
    HUGE_MUSHROOM_1(99, SOLID, AXE),
    HUGE_MUSHROOM_2(100, SOLID, AXE),
    IRON_FENCE(101, SOLID, PICKAXE),
    THIN_GLASS(102, SOLID, PICKAXE),
    MELON_BLOCK(103, SOLID, AXE),
    PUMPKIN_STEM(104, PLACEABLE),
    MELON_STEM(105, PLACEABLE),
    VINE(106, PLACEABLE),
    FENCE_GATE(107, SOLID, AXE),
    BRICK_STAIRS(108, SOLID, PICKAXE),
    SMOOTH_STAIRS(109, SOLID, PICKAXE),
    MYCEL(110, SOLID, SHOVEL),
    WATER_LILY(111, SOLID),
    NETHER_BRICK(112, SOLID, PICKAXE),
    NETHER_FENCE(113, SOLID, PICKAXE),
    NETHER_BRICK_STAIRS(114, SOLID, PICKAXE),
    NETHER_WARTS(115, PLACEABLE),
    ENCHANTMENT_TABLE(116, SOLID, PICKAXE),
    BREWING_STAND(117, SOLID, PICKAXE),
    CAULDRON(118, SOLID, PICKAXE),
    ENDER_PORTAL(119, INDESTRUCTABLE),
    ENDER_PORTAL_FRAME(120, INDESTRUCTABLE | SOLID | PLACEABLE),
    ENDER_STONE(121, PICKAXE),
    DRAGON_EGG(122, SOLID | INTERACTABLE),
    REDSTONE_LAMP_OFF(123, PICKAXE),
    REDSTONE_LAMP_ON(124, SOLID, PICKAXE),
    WOOD_DOUBLE_STEP(125, SOLID, AXE),
    WOOD_STEP(126, SOLID, AXE),
    COCOA(127),
    SANDSTONE_STAIRS(128, SOLID, PICKAXE),
    EMERALD_ORE(129, SOLID, PICKAXE),
    ENDER_CHEST(130, INDESTRUCTABLE | INTERACTABLE | SOLID | PLACEABLE),
    TRIPWIRE_HOOK(131, INTERACTABLE | PLACEABLE),
    TRIPWIRE(132, PLACEABLE),
    EMERALD_BLOCK(133, PICKAXE),
    SPRUCE_WOOD_STAIRS(134, SOLID, AXE),
    BIRCH_WOOD_STAIRS(135, SOLID, AXE),
    JUNGLE_WOOD_STAIRS(136, SOLID, AXE),
    COMMAND(137, SOLID),
    BEACON(138, SOLID),
    COBBLE_WALL(139, SOLID, PICKAXE),
    FLOWER_POT(140),
    CARROT(141, PLACEABLE),
    POTATO(142, PLACEABLE),
    WOOD_BUTTON(143, INTERACTABLE | PLACEABLE, AXE),
    SKULL(144),
    ANVIL(145, SOLID, PICKAXE);

    private final int id, maxStack, flags;
    private final ToolType toolType;

    private Material(int id) {
        this(id, SOLID | PLACEABLE);
    }

    private Material(int id, ToolType toolType) {
        this(id, SOLID | PLACEABLE, 64, toolType);
    }

    private Material(int id, int flags) {
        this(id, flags, 64);
    }

    private Material(int id, int flags, ToolType toolType) {
        this(id, flags, 64, toolType);
    }

    private Material(int id, int flags, int maxStack) {
        this(id, flags, maxStack, null);
    }

    private Material(int id, int flags, int maxStack, ToolType toolType) {
        this.id = id;
        this.flags = flags;
        this.maxStack = maxStack;
        this.toolType = toolType;
    }

    public int getId() {
        return id;
    }

    public int getMaxStack() {
        return maxStack;
    }

    public boolean isSolid() {
        return (flags & SOLID) == SOLID;
    }

    public boolean isInteractable() {
        return (flags & INTERACTABLE) == INTERACTABLE;
    }

    public boolean isPlaceable() {
        return (flags & PLACEABLE) == PLACEABLE;
    }

    public boolean isIndestructable() {
        return (flags & INDESTRUCTABLE) == INDESTRUCTABLE;
    }

    public ToolType getToolType() {
        return toolType;
    }

    public static Material getById(int id) {
        for (Material type : values()) {
            if (type.getId() == id) {
                return type;
            }
        }
        return UNKNOWN;
    }

    protected static final class Flag {

        public static final int SOLID = 1, INTERACTABLE = 2, PLACEABLE = 4, INDESTRUCTABLE = 8;
    }

}
