---
- name: Start diskstat collection
  gather_facts: true
  hosts: all
  become: "{{ use_sudo }}"
  tasks:
    - name: Set fact for ANSIBLE_USE_SUDO
      set_fact:
        ansible_use_sudo: "{{ lookup('env', 'ANSIBLE_USE_SUDO') | default('false') == 'true' }}"
    - name: Make diskstat executable
      shell:
        cmd: chmod +x {{wd}}/collect_diskstat.sh
        chdir: "{{wd}}"
    - name: Run diskstat collection script in the background under privelledged access
      shell:
        cmd: |
          nohup sh -c "sudo ./collect_diskstat.sh | sudo tee -a diskstat.csv" > /dev/null &
          NOHUP_PID=$!
          sleep 1
          DISKSTAT_PID=$(pgrep -P $NOHUP_PID "./collect_diskstat.sh")
          echo $DISKSTAT_PID > diskstat.pid
        chdir: "{{wd}}"
      when: ansible_use_sudo == true
    - name: Run diskstat collection script in the background under non-privelledged access
      shell:
        cmd: |
          nohup c "./collect_diskstat.sh | tee -a diskstat.csv" > /dev/null &
          echo $! > diskstat.pid
        chdir: "{{wd}}"
      when: ansible_use_sudo != true
    - name: Verify diskstat collection process is running
      shell:
        cmd: pgrep -f collect_diskstat.sh || echo "Diskstat script not running!"
