---
- name: Start diskstat collection
  gather_facts: true
  hosts: all
  tasks:
    - name: Make diskstat executable
      shell:
        cmd: chmod +x {{wd}}/collect_diskstat.sh
        chdir: "{{wd}}"
    - name: Run diskstat collection script in the background
      shell:
        cmd: |
          nohup ./collect_diskstat.sh &>> diskstat.csv &
          echo $! > diskstat.pid
        chdir: "{{wd}}"
    - name: Verify diskstat collection process is running
      shell:
        cmd: pgrep -f collect_diskstat.sh || echo "Diskstat script not running!"
