---
- name: Stop Telegraf
  gather_facts: true
  hosts: all
  tasks:
    - name: Lookup Telegraf PID
      shell: cat {{ wd }}/telegraf-{{ inventory_hostname }}.pid
      register: telegraf_pid
      ignore_errors: yes

    - name: Stop Telegraf if running
      shell: kill {{ telegraf_pid.stdout }}
      when: telegraf_pid.stdout is defined
      ignore_errors: yes

    - name: Ensure Telegraf is stopped
      shell: pkill -f telegraf || true
      ignore_errors: yes

    - name: Remove PID file
      file:
        path: "{{ wd }}/telegraf-{{ inventory_hostname }}.pid"
        state: absent
      ignore_errors: yes
