---
- name: Start Telegraf
  gather_facts: true
  hosts: all
  become: "{{ lookup('env', 'ANSIBLE_USE_SUDO') | default('false') == 'true' }}"
  become_method: sudo
  become_user: root
  tasks:
    - name: Find executable
      shell: |
        find {{wd}} -type f -executable -name telegraf
      register: find_telegraf
    - name: Run Telegraf
      shell:
        cmd: |
          nohup {{find_telegraf.stdout}} --config telegraf-{{inventory_hostname}}.conf --pidfile {{wd}}/telegraf-{{inventory_hostname}}.pid &> telegraf.log &
        chdir: "{{wd}}"
