---
- name: Deploy PaperMC
  gather_facts: true
  hosts: all
  tasks:
    - name: Run PaperMC
      shell:
        cmd: |
          module load java/jdk-17 || true # just in case we are on DAS
          nohup java -javaagent:jolokia-agent-jvm-2.0.3-javaagent.jar -jar paper-1.20.1-58.jar &> /dev/null &
          echo $! > papermc.pid
        chdir: "{{ wd }}"
    - name: Waiting for server to become ready
      wait_for:
        path: "{{wd}}/logs/latest.log"
        search_regex: 'For help, type "help"'
